const getImageUrl = (id: number) =>
  `https://touring-bikes.s3.eu-west-1.amazonaws.com/${id}.jpg`;

export default [
  {
    id: 1,
    title: 'Surly Long Haul Trucker',
    description: 'Long distance cargo bike ready to go anywhere.',
    price: 1350,
    count: 10,
    image: getImageUrl(1),
  },
  {
    id: 2,
    title: 'Kona Sutra 2022',
    description: 'It’s functional. It’s stylish. It’s incredibly versatile.',
    price: 2399,
    count: 3,
    image: getImageUrl(2),
  },
  {
    id: 3,
    title: 'Thorn Sherpa',
    description: 'Strong small-wheeled tourer.',
    price: 1599,
    count: 4,
    image: getImageUrl(3),
  },
  {
    id: 4,
    title: 'TREK 520 DISC',
    description: 'Steel touring bike made for the open road.',
    price: 1799,
    count: 1,
    image: getImageUrl(4),
  },
  {
    id: 5,
    title: 'Ridgeback Panorama',
    description: 'Fully kitted-out tourer with good gearing and quality tyres.',
    price: 1699,
    count: 2,
    image: getImageUrl(5),
  },
  {
    id: 6,
    title: 'Salsa Marrakesh Brooks',
    description: 'Best for heading off road.',
    price: 1499,
    count: 7,
    image: getImageUrl(6),
  },
  {
    id: 7,
    title: 'Fuji Touring LTD',
    description: 'Strong and comfortable to ride.',
    price: 1299,
    count: 8,
    image: getImageUrl(7),
  },
  {
    id: 8,
    title: 'Specialized AWOL Expert',
    description: 'Built to take you far away.',
    price: 2500,
    count: 1,
    image: getImageUrl(8),
  },
  {
    id: 9,
    title: 'Co-op Cycles ADV 1.1',
    description: 'Incredible components for the money.',
    price: 1549,
    count: 5,
    image: getImageUrl(9),
  },
  {
    id: 10,
    title: 'Tommaso Sterrata',
    description: 'Italian Design And Top-Notch Engineering.',
    price: 925,
    count: 3,
    image: getImageUrl(10),
  },
];
